Vagrant.configure("2") do |config|

  config.vm.box = 'precise64-20130827'
  config.vm.box_url = 'http://cloud-images.ubuntu.com/vagrant/precise/20130827/precise-server-cloudimg-amd64-vagrant-disk1.box'

  config.vm.define :es1 do |node|
    node.vm.hostname = "es1"
    node.vm.network :private_network, ip: "10.11.1.10"
    node.vm.provision :shell, :path => "provision-es1.sh"
  end
 
  config.vm.define :es2 do |node|
    node.vm.hostname = "es2"
    node.vm.network :private_network, ip: "10.11.1.11"
    node.vm.provision :shell, :path => "provision-es1.sh"
  end
  
  config.vm.define :es3 do |node|
    node.vm.hostname = "es3"
    node.vm.network :private_network, ip: "10.11.1.12"
    node.vm.provision :shell, :path => "provision-es1.sh"
  end
  
end
